version: '3.8'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filmesdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: filmesdb
      DB_USERNAME: admin
      DB_PASSWORD: senha123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8001:8000"
    command: >
      sh -c "
        composer install &&
        php artisan key:generate &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  # Vue frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0
      "

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
